class AppStrings {
  static String appname = "Mediapp",
      bestDocapp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow =
          "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forget Password ?",
      login = "Login",
      signup = "Signup",
      welcome = "Welcome",
      search = "Search Doctors",
      alreadyHaveAccount = "Account have an account?",
      dontHaveAccount = "Don't have an account?",
      body = "Physiatrists",
      ear = "Otolaryngologists",
      liver = "Hepatologists",
      lungs = "Pulmonologists",
      heart = "Cardiologists",
      kidney = "Nephrologists",
      eye = "Ophthalmologist",
      stomach = "Gastroenterologists",
      tooth = "Dentists",
      doctor = "Doctor Login",
      settings = "Settings",
      changePassword = "Change Password",
      termsConditions = "Terms & Conditions",
      signout = "Signout",
      category = "Category";
}
